name: 'build and deploy production'

on:
  push:
    tags:
      - '*'

jobs:
  build-production-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'
      - run: npm ci
      - run: npm run build

      - name: Upload dist folder artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-production
          path: dist
